name: Read hello.txt file

on:
  push:
    branches:
      - main

jobs:
  read-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Read and display hello.txt
      run: |
        echo "Reading hello.txt content:"
        cat hello.txt